[package]
name = "fcpm"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["fcpm-test"]
resolver = "3"

[workspace.dependencies]
tempfile = "3"
thiserror = "2"
test-log = "0.2"

[dependencies]
thiserror.workspace = true
rusqlite = { version = "0.37", features = ["bundled"] }
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
reqwest = { version = "0.12", features = [
    "blocking",
    "rustls-tls",
], default-features = false, optional = true }
log = { version = "0.4", optional = true }

[features]
default = ["http"]
all = ["logging", "http"]
logging = ["dep:log"]
http = ["dep:reqwest"]

[dev-dependencies]
tempfile.workspace = true
test-log.workspace = true
fcpm-test = { path = "fcpm-test" }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
